# vlsp-2023-vllm/lambada_vi

In [7]:
import pandas as pd

splits = {'test': 'data/test-00000-of-00001-0f570d0544259679.parquet', 'validation': 'data/validation-00000-of-00001-07192d6d50b20f30.parquet'}
df_lambada_test = pd.read_parquet("hf://datasets/vlsp-2023-vllm/lambada_vi/" + splits["test"])
df_lambada_val = pd.read_parquet("hf://datasets/vlsp-2023-vllm/lambada_vi/" + splits["validation"])

In [8]:
df_lambada_test.head(5)

,text,context,target_word,metadata
0,Lâm nghiệp hay Vào rừng! ~ Chuyện vặt mỗi ngày...,Lâm nghiệp hay Vào rừng! ~ Chuyện vặt mỗi ngày...,2014,"{'num_sents': 6, 'target_word': {'appeared_in_..."
1,"Ngày 1 tháng 1 năm 1962, một phần của Herøy tr...","Ngày 1 tháng 1 năm 1962, một phần của Herøy tr...",Herøy,"{'num_sents': 3, 'target_word': {'appeared_in_..."
2,Sau hai cuộc chiến tranh Balkan vào năm 1912 v...,Sau hai cuộc chiến tranh Balkan vào năm 1912 v...,vương quốc,"{'num_sents': 5, 'target_word': {'appeared_in_..."
3,Nguỵ lược () là một sử liệu Trung Quốc do Ngư ...,Nguỵ lược () là một sử liệu Trung Quốc do Ngư ...,cổ đại,"{'num_sents': 3, 'target_word': {'appeared_in_..."
4,Phần phía trước của tàu vũ trụ có chứa một thi...,Phần phía trước của tàu vũ trụ có chứa một thi...,nhất,"{'num_sents': 11, 'target_word': {'appeared_in..."

In [9]:
df_lambada_val.head(5)

,text,context,target_word,metadata
0,"Tại UEFA Nations League 2020-21, do UEFA sửa đ...","Tại UEFA Nations League 2020-21, do UEFA sửa đ...",Nations League,"{'num_sents': 10, 'target_word': {'appeared_in..."
1,"Ngày 17 tháng 9 năm 1939, sức kháng cự của Ba ...","Ngày 17 tháng 9 năm 1939, sức kháng cự của Ba ...",máu,"{'num_sents': 4, 'target_word': {'appeared_in_..."
2,Y Lê (Ili) là tên gọi một vùng đất xung quanh ...,Y Lê (Ili) là tên gọi một vùng đất xung quanh ...,nơi,"{'num_sents': 12, 'target_word': {'appeared_in..."
3,"Đến tháng 4 năm 1512, Lê Hy, Trịnh Hưng, Lê Mi...","Đến tháng 4 năm 1512, Lê Hy, Trịnh Hưng, Lê Mi...",giặc,"{'num_sents': 4, 'target_word': {'appeared_in_..."
4,Hầu hết các nhà sử học hiện đại không sử dụng ...,Hầu hết các nhà sử học hiện đại không sử dụng ...,ít,"{'num_sents': 7, 'target_word': {'appeared_in_..."

# vlsp-2023-vllm/wikipediaqa_vi

In [10]:
import pandas as pd

df_wiki_qa_test = pd.read_parquet("hf://datasets/vlsp-2023-vllm/wikipediaqa_vi/data/test-00000-of-00001-87b0058c89924d90.parquet")

In [11]:
df_wiki_qa_test.head(5)

,question,choices,answerKey,metadata
0,Hai ca sĩ nào đã song ca với nhau trong ca khú...,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Bri...",A,ai_la_trieu_phu
1,Quá liều thuốc có thể dẫn đến những hậu quả gì?,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Ngộ...",C,health
2,Toà án Công lý Quốc tế có trụ sở tại nước nào?,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Thụ...",D,ai_la_trieu_phu
3,Dushanbe là thủ đô của Tajikistan. Tên gọi lấy...,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Thứ...",D,ai_la_trieu_phu
4,Chính phủ Pháp cử tướng Nava sang Đông Dương đ...,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Chỉ...",C,people

# vlsp-2023-vllm/exams_vi

In [12]:
import pandas as pd

df_exams_vi_test = pd.read_parquet("hf://datasets/vlsp-2023-vllm/exams_vi/data/test-00000-of-00001-42f8c598c597c3c1.parquet")

In [16]:
df_exams_vi_test.head(5)

,question,id,choices,answerKey,metadata
0,"Biển Đông mang lại nguồn nhiệt ẩm dồi dào, lượ...",64249f34d6787ebbb4dc2f14e81a23a0,"{'label': ['A', 'B', 'C', 'D'], 'text': ['Có t...",C,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"
1,Khó khăn lớn nhất về mặt tự nhiên đối với việc...,b10230c9d382c2d12a671c51f562b0db,"{'label': ['A', 'B', 'C', 'D'], 'text': ['đất ...",B,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"
2,Ý nghĩa chủ yếu của việc tăng cường chuyên môn...,1b2009ae23fa39ccb5e4c59d6429e388,"{'label': ['A', 'B', 'C', 'D'], 'text': ['tạo ...",D,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"
3,Hướng phát triển chủ đạo của ngành bưu chính t...,ef5e864a375b0cfa534da08e2fca6eec,"{'label': ['A', 'B', 'C', 'D'], 'text': ['đẩy ...",B,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"
4,Đất ở đâu trai hiền gái lịch\nNon xanh nước bi...,a0960f186d97d94ff6072af47e09232e,"{'label': ['A', 'B', 'C', 'D'], 'text': ['Cần ...",D,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"

# vlsp-2023-vllm/comprehension

In [17]:
import pandas as pd

df_comprehension_test = pd.read_parquet("hf://datasets/vlsp-2023-vllm/comprehension/data/test-00000-of-00001-192ecf7907721b26.parquet")

'The read operation timed out' thrown while requesting GET https://huggingface.co/datasets/vlsp-2023-vllm/comprehension/resolve/main/data/test-00000-of-00001-192ecf7907721b26.parquet
Retrying in 1s [Retry 1/5].

In [ ]:
df_comprehension_test.head(5)