# vlsp-2023-vllm/lambada_vi

In [1]:
import pandas as pd

splits = {'test': 'data/test-00000-of-00001-0f570d0544259679.parquet', 'validation': 'data/validation-00000-of-00001-07192d6d50b20f30.parquet'}
df_lambada_test = pd.read_parquet("hf://datasets/vlsp-2023-vllm/lambada_vi/" + splits["test"])
df_lambada_val = pd.read_parquet("hf://datasets/vlsp-2023-vllm/lambada_vi/" + splits["validation"])

In [9]:
# Show full text in every cell
pd.set_option('display.max_colwidth', None)

# Optional: Show all columns and rows without truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [10]:
df_lambada_test.head(1)

,text,context,target_word,metadata
0,"Lâm nghiệp hay Vào rừng! ~ Chuyện vặt mỗi ngày ở xã Kamusari (tiếng Anh: ""Wood Job!)"" là bộ phim điện ảnh hài hước Nhật Bản năm 2014, được biên soạn và đạo diễn bởi Shinobu Yaguchi, dựa trên tiểu thuyết có tên là của nhà văn người Nhật Shion Miura. Các diễn viên bao gồm Shota Sometani, Masami Nagasawa, và Hideaki Ito. Ca khúc chính trong phim là ""Happiest Fool"" (tạm dịch: Chàng khờ hạnh phúc nhất), được trình bài bởi Maia Hirasawa. Bộ phim được ra mắt ngày 10 tháng 5 năm 2014, và ra mắt tại Bắc Mỹ tại Liên hoan phim LA Eigafest 2014","Lâm nghiệp hay Vào rừng! ~ Chuyện vặt mỗi ngày ở xã Kamusari (tiếng Anh: ""Wood Job!)"" là bộ phim điện ảnh hài hước Nhật Bản năm 2014, được biên soạn và đạo diễn bởi Shinobu Yaguchi, dựa trên tiểu thuyết có tên là của nhà văn người Nhật Shion Miura. Các diễn viên bao gồm Shota Sometani, Masami Nagasawa, và Hideaki Ito. Ca khúc chính trong phim là ""Happiest Fool"" (tạm dịch: Chàng khờ hạnh phúc nhất), được trình bài bởi Maia Hirasawa. Bộ phim được ra mắt ngày 10 tháng 5 năm 2014, và ra mắt tại Bắc Mỹ tại Liên hoan phim LA Eigafest",2014,"{'num_sents': 6, 'target_word': {'appeared_in_prev_sents': True, 'pos_tag': 'M'}, 'title': 'Wood Job!', 'url': 'https://vi.wikipedia.org/wiki?curid=9148887', 'word_type': 'single_word'}"

In [12]:
df_lambada_val.head(1)

,text,context,target_word,metadata
0,"Tại UEFA Nations League 2020-21, do UEFA sửa đổi thể thức nên Đức không bị xuống hạng, Đức nằm cùng bảng A4 với Tây Ban Nha, Thuỵ Sĩ & Ukraina, Đức hoà Tây Ban Nha 1-1 tại sân nhà, hoà Thuỵ Sĩ cùng tỷ số tại Basel, thắng Ukraina 2-1 tại Kiev, họ để Thuỵ Sĩ cầm hoà 3-3, thắng Ukraina 3-1 tại sân nhà sau đó thua sốc Tây Ban Nha 0-6 tại Seville. Theo UEFA, đây là trận thua thảm hoạ lịch sử đối với bóng đá Đức. Lần gần nhất họ thua cách biệt tới 5 bàn trong một trận đấu là ở World Cup 1954 (thua Hungary 3-8 ở vòng bảng). Lùi xa hơn thì vào năm 1931, Đức thua Áo 0-6 trong một trận giao hữu. Thế nên trận thua 0-6 là trận thua đậm nhất lịch sử của đội tuyển Đức trong một trận đấu quốc tế thuộc FIFA. Thất bại được xem là đậm nhất lịch sử của Đức đến nay được ghi nhận là trận thua 0-9 trước Anh vào năm 1909, ở giải quốc tế Đức lần thứ 4. Nhưng khi đó bóng đá vẫn là nghiệp dư. Đây là lần đầu tiên trong lịch sử đội tuyển Đức thua tới 6 bàn không gỡ. Cả trận, họ hứng chịu 23 cú dứt điểm và 10 trong số đó hướng trúng khung thành. Trận thua này khiến Đức dừng bước tại Nations League","Tại UEFA Nations League 2020-21, do UEFA sửa đổi thể thức nên Đức không bị xuống hạng, Đức nằm cùng bảng A4 với Tây Ban Nha, Thuỵ Sĩ & Ukraina, Đức hoà Tây Ban Nha 1-1 tại sân nhà, hoà Thuỵ Sĩ cùng tỷ số tại Basel, thắng Ukraina 2-1 tại Kiev, họ để Thuỵ Sĩ cầm hoà 3-3, thắng Ukraina 3-1 tại sân nhà sau đó thua sốc Tây Ban Nha 0-6 tại Seville. Theo UEFA, đây là trận thua thảm hoạ lịch sử đối với bóng đá Đức. Lần gần nhất họ thua cách biệt tới 5 bàn trong một trận đấu là ở World Cup 1954 (thua Hungary 3-8 ở vòng bảng). Lùi xa hơn thì vào năm 1931, Đức thua Áo 0-6 trong một trận giao hữu. Thế nên trận thua 0-6 là trận thua đậm nhất lịch sử của đội tuyển Đức trong một trận đấu quốc tế thuộc FIFA. Thất bại được xem là đậm nhất lịch sử của Đức đến nay được ghi nhận là trận thua 0-9 trước Anh vào năm 1909, ở giải quốc tế Đức lần thứ 4. Nhưng khi đó bóng đá vẫn là nghiệp dư. Đây là lần đầu tiên trong lịch sử đội tuyển Đức thua tới 6 bàn không gỡ. Cả trận, họ hứng chịu 23 cú dứt điểm và 10 trong số đó hướng trúng khung thành. Trận thua này khiến Đức dừng bước tại",Nations League,"{'num_sents': 10, 'target_word': {'appeared_in_prev_sents': True, 'pos_tag': 'Np'}, 'title': 'Đội tuyển bóng đá quốc gia Đức', 'url': 'https://vi.wikipedia.org/wiki?curid=44007', 'word_type': 'compound_word'}"

# vlsp-2023-vllm/wikipediaqa_vi

In [13]:
import pandas as pd

df_wiki_qa_test = pd.read_parquet("hf://datasets/vlsp-2023-vllm/wikipediaqa_vi/data/test-00000-of-00001-87b0058c89924d90.parquet")

In [14]:
df_wiki_qa_test.head(5)

,question,choices,answerKey,metadata
0,Hai ca sĩ nào đã song ca với nhau trong ca khúc “Me against the music”?,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Britney và Madonna', 'Britney và Christina aguilera', 'Christina aguilera và Madonna', 'Britney và Taylor Swift']}",A,ai_la_trieu_phu
1,Quá liều thuốc có thể dẫn đến những hậu quả gì?,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Ngộ độc', 'Tử vong', 'Cả A và B', 'Không có hậu quả gì']}",C,health
2,Toà án Công lý Quốc tế có trụ sở tại nước nào?,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Thụy Sĩ', 'Pháp', 'Mỹ', 'Hà Lan']}",D,ai_la_trieu_phu
3,Dushanbe là thủ đô của Tajikistan. Tên gọi lấy từ một từ tiếng Ba Tư có nghĩa là gì?,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Thứ sáu', 'Thứ bảy', 'Chủ nhật', 'Thứ hai']}",D,ai_la_trieu_phu
4,Chính phủ Pháp cử tướng Nava sang Đông Dương đảm nhiệm chức vụ gì?,"{'labels': ['A', 'B', 'C', 'D'], 'text': ['Chỉ huy quân đội Pháp ở Đông Dương', 'Cao ủy Pháp ở Đông Dương', 'Tổng chỉ huy quân đội viễn chinh Pháp ở Đông Dương', 'Tổng chỉ huy Đông Dương']}",C,people

# vlsp-2023-vllm/exams_vi

In [15]:
import pandas as pd

df_exams_vi_test = pd.read_parquet("hf://datasets/vlsp-2023-vllm/exams_vi/data/test-00000-of-00001-42f8c598c597c3c1.parquet")

In [16]:
df_exams_vi_test.head(5)

,question,id,choices,answerKey,metadata
0,"Biển Đông mang lại nguồn nhiệt ẩm dồi dào, lượng mưa lớn cho nước ta chủ yếu do biển Đông có đặc điểm gì?",64249f34d6787ebbb4dc2f14e81a23a0,"{'label': ['A', 'B', 'C', 'D'], 'text': ['Có thềm lục địa mở rộng hai đầu thu hẹp ở giữa', 'Biển kín với các hải lưu chạy khép kín', 'Nóng, ẩm và chịu ảnh hưởng của gió mùa', 'Có diện tích lớn gấp 3 lần đất liền']}",C,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"
1,Khó khăn lớn nhất về mặt tự nhiên đối với việc phát triển kinh tế - xã hội của vùng đồi núi là gì?,b10230c9d382c2d12a671c51f562b0db,"{'label': ['A', 'B', 'C', 'D'], 'text': ['đất trồng cây lương thực bị hạn chế', 'địa hình bị chia cắt mạnh, nhiều sông suối, hẻm vực trở ngại cho giao thông', 'khí hậu phân hoá phức tạp', 'khoáng sản có nhiều mỏ trữ lượng nhỏ, phân tán trong không gian']}",B,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"
2,Ý nghĩa chủ yếu của việc tăng cường chuyên môn hóa sản xuất nông nghiệp ở nước ta là gì?,1b2009ae23fa39ccb5e4c59d6429e388,"{'label': ['A', 'B', 'C', 'D'], 'text': ['tạo thêm nhiều việc lâm cho số lượng lớn người lao động,', 'đáp ứng tốt nhu cầu chuyển dịch cơ cấu ngành và lãnh thổ', 'khai thác có hiệu quả sự đa dạng, phong phú của tự nhiên', 'tạo ra khối lượng nông sản hàng hóa lớn và có chất lượng']}",D,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"
3,Hướng phát triển chủ đạo của ngành bưu chính trong thời gian tới là gì?,ef5e864a375b0cfa534da08e2fca6eec,"{'label': ['A', 'B', 'C', 'D'], 'text': ['đẩy mạnh các hoạt động công ích phục vụ xã hội', 'đẩy mạnh các hoạt động kinh doanh', 'phát triển mạng lưới sang các nước khác', 'tăng cường xây dựng các cơ sở văn hóa tại vùng nông thôn']}",B,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"
4,"Đất ở đâu trai hiền gái lịch\nNon xanh nước biếc, điện ngọc đền rồng\nTháp bảy tầng, Thánh miếu, chùa Ông\nChuông khua Diệu Đế, trông rung Tam Tòa?",a0960f186d97d94ff6072af47e09232e,"{'label': ['A', 'B', 'C', 'D'], 'text': ['Cần Thơ', 'Bến Tre', 'Đà Nẵng', 'Thừa Thiên']}",D,"{'grade': 'Lớp 12', 'subject': 'MÔN ĐỊA'}"

# vlsp-2023-vllm/comprehension

In [17]:
import pandas as pd

df_comprehension_test = pd.read_parquet("hf://datasets/vlsp-2023-vllm/comprehension/data/test-00000-of-00001-192ecf7907721b26.parquet")

In [18]:
df_comprehension_test.head(5)

,question,id,choices,answerKey
0,"Trong một quần xã rừng tự nhiên ở vùng Đông Nam Á, các loài động vật ăn có cỡ lớn như bò rừng mỗi khi di chuyển thường đánh động và làm các loài côn trùng bay khỏi tổ. Lúc này, các loài chim như diệc bạc sẽ bắt các côn trùng bay khỏi tổ làm thức ăn. Việc côn trùng bay khỏi tổ cũng như việc chim diệc bạc bắt côn trùng không ảnh hưởng gì đến đời sống bò rừng. Chim gõ bò có thể bắt ve bét trên da bò rừng làm thức ăn. \nMối quan hệ giữa diệc bạc và côn trùng dẫn đến hiện tượng gì?",7b90afc536ed33e86061cc55f15f6a14,"{'label': ['A', 'B', 'C', 'D'], 'text': ['Cạnh tranh khác loài', 'Khống chế sinh học', 'Nhập cư- di cư', 'Hiệu ứng thắt cổ chai']}",B
1,"Dựa vào thông tin sau trả lời câu hỏi:\nĐể đối phó với chiến lược ""Chiến tranh đặc biệt"" của Mỹ, trên cơ sở thế và lực mới do cao trào ""Đồng khởi"" tạo ra, ngày 31-1-1961 Bộ Chính trị đã ra Chỉ thị ""Về phương hướng và nhiệm vụ công tác trước mắt của cách mạng miền Nam"". Ngày 15-2-1961, các tổ chức vũ trang miền Nam đã thống nhất thành ""Quân giải phóng miền Nam Việt Nam"". Từ đây các cuộc khởi nghĩa từng phần phát triển lên thành cuộc chiến tranh cách mạng trên quy mô toàn miền. Ở đô thị, phong trào đấu tranh của CNLĐ, thanh niên, học sinh, sinh viên, trí thức, đồng bào các tôn giáo... làm lung lay ý chí bọn xâm lược, tay sai. Đồng bào ta ở những vùng bị gom kiên quyết đấu tranh, bám đất, bám làng, nêu cao khẩu hiệu ""một tấc không đi, một li không rời"". Điển hình là phong trào đấu tranh chống gom dân của đồng bào ấp Bầu Mây, xã An Tịnh (huyện Trảng Bàng - Tây Ninh), của đồng bào Cai Lậy (Mỹ Tho), của đồng bào Khmer tỉnh Trà Vinh và An Giang, cuộc đấu tranh chống địch rải chất độc hóa học của nhân dân huyện Châu Thành (Bến Tre)...\n Ở miền Bắc, thực hiện kế hoạch 5 năm lần thứ nhất, các phong trào thi đua sôi nổi ""Tất cả vì miền Nam ruột thịt"" ở khắp các địa phương, các cấp, các ngành đã đưa miền Bắc trở thành căn cứ địa vững chắc cho cách mạng Việt Nam, với lực lượng kinh tế quốc phòng lớn mạnh. Để phục vụ cách mạng miền Nam, miền Bắc không ngừng chi viện sức người, sức của cho miền Nam.\n Trong những năm 1961 - 1964, nhân dân miền Nam vừa đấu tranh, vừa chú trọng xây dựng LLVT cách mạng với sự chi viện đắc lực từ miền Bắc đã liên tiếp giành được những thắng lợi trên các chiến trường. Điển hình là trận ấp Bắc (2-1-1963), chiến dịch Bình Giã (2/12/1964 - 3/1/1965), Ba Gia (28/5 - 20/7/1965), Đồng Xoài (10/5 - 22/7/1965). Với những thất bại liên tiếp của nguỵ quân, nguỵ quyền, cuối năm 1963, cùng với sự kiện Tổng thống Mỹ Jôn Ken-nơ-đi bị ám sát, Giôn-xơn lên nắm quyền ở Mỹ, buộc chúng phải ""thay ngựa giữa dòng"" bằng việc phế bỏ Diệm - Nhu, làm cho nền chính trị tay sai của Mỹ lâm vào cuộc khủng hoảng triền miên. Chỉ trong hơn một năm rưỡi (11-1963 - 6-1965) đã có 14 lần đảo chính và phản đảo chính ở miền Nam. Bộ trưởng Quốc phòng Mỹ Mắc Na-ma-ra từ miền Nam Việt Nam về đã báo cáo trước Nhà trắng và Quốc hội Mỹ rằng"" Quân lực Việt Nam Cộng hòa đã không còn đủ sức chiến đấu, chế độ Sài Gòn đã thất bại"". \n Ngày 5-8-1964, đế quốc Mỹ mở cuộc chiến tranh phá hoại miền Bắc bằng không quân và hải quân hòng ngăn chặn sự chi viện của ""hậu phương lớn"" cho ""tiền tuyến lớn"". Ngay trong ngày, chúng dùng 64 lần chiếc máy bay mở cuộc tiến công ""Mũi tên xuyên"" đánh ồ ạt các khu vực sông Gianh (Quảng Bình), Cửa Hội (thành phố Vinh), Lạch Trường (Thanh Hóa), Bãi Cháy (Quảng Ninh). Ngay trận đầu, 8 máy bay phản lực Mỹ bị bắn rơi. Trong 3 tháng đầu năm 1965 đã có 440 máy bay Mỹ bị bắn rơi trên miền Bắc. Ngày 5/8 trở thành ngày truyền thống đánh thắng trận đầu của bộ đội Hải quân nhân dân Việt Nam. Chiến thắng 5-8-1964 cổ vũ mạnh mẽ khí thế chiến đấu, củng cố niềm tin và khẳng định ý chí quyết tâm đánh thắng cuộc chiến tranh phá hoại bằng không quân và hải quân của đế quốc Mỹ của nhân dân ta.\n Trước những thắng lợi vang dội của ta ở cả hai miền Nam - Bắc, chiến lược ""Chiến tranh đặc biệt"" của Mỹ đã hoàn toàn thất bại, buộc Mỹ phải ồ ạt đưa quân viễn chinh vào miền Nam để thực hiện chiến lược ""Chiến tranh cục bộ"" hòng cứu vãn thế sụp đổ. Từ đây, cách mạng miền Nam chuyển sang giai đoạn mới.\nTrong giai đoạn 1960-1965, Mỹ thực hiện chiến lược chiến tranh nào?",dba60d2561edfcfe92480dc52b108ad0,"{'label': ['A', 'B', 'C', 'D'], 'text': ['Chiến lược chiến tranh đơn phương', 'Chiến lược chiến tranh đặc biệt', 'Chiến lược chiến tranh cục bộ', 'Chiến lược Việt Nam hóa chiến tranh']}",B
2,"Dựa vào thông tin và trả lời các câu hỏi:\n Trận đánh gây được tiếng vang lúc bấy giờ là trận phục kích của quân ta tại Cầu Giấy ngày 21-12-1873.\nThừa lúc Gác-ni-ê đem quân xuống đánh Nam Định, việc canh phòng Hà Nội sơ hở, quân ta do Hoàng Tá Viêm chỉ huy (có sự phối hợp với đội quân Cờ đen của Lưu Vĩnh Phúc) từ Sơn Tây kéo về Hà Nội, hình thành trận tuyến bao vây quân địch. Nghe tin đó, Gác-ni-ê phải tức tốc đưa quân vào sát thành Hà Nội khiêu chiến. Gác-ni-ê de quân đuổi theo. Rơi vào ổ phục kích của quân ta tại khu vực Cầu Giấy, toán quân Pháp, trong đó có Gác-ni-ê, đã bị tiêu diệt.\nChiến thắng Cầu Giấy lần thứ nhất khiến cho nhân dân ta vô cùng phấn khởi; ngược lại, làm cho thực dân Pháp hoang mang, lo sợ và tìm cách thương lương. Triều đình lại kí Hiệp ước năm 1874 (Hiệp ước Giáp Tuất), theo đó quân Pháp rút khỏi Hà Nội và các tỉnh đồng bằng Bắc Kì, nhưng vẫn có điều kiện tiếp tục xây dựng cơ sở để thực hiện các bước xâm lược về sau.\n(SGK Lịch sử 11, trang 118-119)\nTrận đánh quân ta gây được tiếng vang tại Cầu Giấy khi nào?",dbe4b1418cf2c5e5f53ca53589f15fb6,"{'label': ['A', 'B', 'C', 'D'], 'text': ['Ngày 20-12-1873', 'Ngày 21-12-1873', 'Ngày 22-12-1873', 'Ngày 23-12-1873']}",B
3,"Dựa vào thông tin và trả lời các câu hỏi:\nChủ nghĩa Mác - Lênin và các tài liệu tuyên truyền của Nguyễn Ái Quốc được giai cấp công nhân và nhân dân Việt Nam đón nhận như ''người đi đường đang khát mà có nước uống, đang đói mà có cơm ăn''. Nó lôi cuốn những người yêu nước Việt Nam đi theo con đường cách mạng vô sản; làm dấy lên cao trào đấu tranh mạnh mẽ, sôi nổi khắp cả nước, trong đó giai cấp công nhân ngày càng trở thành một lực lượng chính trị độc lập. Sự truyền bá chủ nghĩa Mác - Lênin vào phong trào quần chúng và phong trào công nhân, làm cho phong trào đấu tranh của giai cấp công nhân và các tầng lớp nhân dân phát triển mạnh mẽ, đòi hỏi phải có tổ chức đảng chính trị lãnh đạo. Vì vậy, các tổ chức cộng sản lần lượt được thành lập:\n- Ngày 17-6-1929, Đông Dương Cộng sản Đảng được thành lập ở Bắc Kỳ.\n- Ngày 25-7-1929, An Nam Cộng sản Đảng được thành lập ở Nam Kỳ.\n- Tháng 9-1929, Đông Dương Cộng sản Liên đoàn được thành lập ở Trung Kỳ.\nNhư vậy, chỉ trong một thời gian ngắn, ở Việt Nam đã có ba tổ chức cộng sản tuyên bố thành lập. Điều đó phản ánh xu thế tất yếu của phong trào đấu tranh cách mạng ở Việt Nam, đồng thời sự tồn tại của ba tổ chức cộng sản hoạt động biệt lập trong một quốc gia có nguy cơ dẫn đến chia rẽ lớn. Yêu cầu bức thiết của cách mạng đặt ra là cần có một đảng cộng sản duy nhất để lãnh đạo phong trào cách mạng của giai cấp công nhân và nhân dân Việt Nam. Lãnh tụ Nguyền Ái Quốc - cán bộ của Quốc tế Cộng sản, người chiến sĩ cách mạng lỗi lạc của dân tộc Việt Nam - là người duy nhất có đủ năng lực và uy tín đáp ứng yêu cầu thống nhất các tổ chức cộng sản.\nTừ ngày 06-01 đến ngày 07-02-1930, Hội nghị hợp nhất ba tổ chức cộng sản họp tại bán đảo Cửu Long (Hương Cảng, Trung Quốc) dưới sự chủ trì của đồng chí Nguyễn Ái Quốc (dưới tên gọi là Vương - thay mặt Quôc tế cộng sản). Hội nghị nhất trí thành lập một đảng thống nhất, lấy tên là Đảng Cộng sản Việt Nam; thông qua Chánh cương vắn tắt, Sách lược vắn tắt, Chương trình tóm tắt, Điều lệ vắn tắt của Đảng.\nHội nghị hợp nhất các tổ chức cộng sản Việt Nam mang tầm vóc lịch sử như là Đại hội thành lập Đảng. Đảng Cộng sản Việt Nam được thành lập là kết quả của cuộc đấu tranh giai cấp và đấu tranh dân tộc ở nước ta trong những năm đầu thế kỷ XX; là sản phẩm của sự kết hợp chủ nghĩa Mác - Lênin với phong trào công nhân và phong trào yêu nước; là kết quả của quá trình lựa chọn, sàng lọc nghiêm khắc của lịch sử và của quá trình chuẩn bị đầy đủ về chính trị, tư tưởng và tổ chức của một tập thể chiến sĩ cách mạng, đứng đầu là đồng chí Nguyễn Ái Quốc.\n(Theo Minh Quang, báo công an thành phố Hà Nội)\nChủ nghĩa Mác-Lênin và các tài liệu tuyên truyền của ai được giai cấp công nhân và nhân dân Việt Nam đón nhận như thế nào?",3562a998d0f748b020c103864fb32044,"{'label': ['A', 'B', 'C', 'D'], 'text': ['Nguyễn Ái Quốc', 'Phan Bội Châu', 'Phan Châu Trinh', 'Trần Phú']}",A
4,"Dựa vào thông tin trong đoạn sau trả lời các câu hỏi:\nNhân dân Việt Nam phải đóng nhiều thứ thuế, mua công trái... Trong 4 năm chiến tranh, chính quyền thuộc địa đã thu được trên 184 triệu ph răng tiền công trái và 14 triệu ph rang tiền quyên góp; ngoài ra, hàng tram tấn lương thực và nông lâm sản các loại, hàng vạn tấn kim loại cần thiết cho chế tạo vũ khí được đưa sang Pháp. Sự cướp bóc ráo riết của thực dân Pháp đã tác động mạnh mẽ đến tình hình kinh tế, xã hội Việt Nam.\nCông nghiệp thuộc địa phải đỡ gánh đỡ những tổn thất, thiếu hụt của chính quốc trong thời gian chiến tranh. Những mỏ đang khai thác nay được bỏ vốn thêm; một số công ty than mới xuất hiện như các công ty than Tuyên Quang (1915), Đông Triều (1916)...\nChiến tranh làm cho hàng hóa nhập khẩu từ Pháp sang Đông Dương giảm hẳn xuống, từ 107 triệu ph rang xuống còn 33 triệu phrăng năm 1918. Để giải quyết khó khăn trên, tư bản Pháp nới lỏng độc quyền, cho tư bản người Việt được kinh doanh tương đối tự do, kiếm cho công thương nghiệp và giao thông vận tải ở Việt Nam có điều kiện phát triển.\n(SGK Lịch sử 11, trang 146)\nSau 4 năm chiến tranh, chính quyền thuộc địa đã thu được bao nhiêu tiền công trái?",752d4b392a6ec316d2dcfc4e1f5b7a74,"{'label': ['A', 'B', 'C', 'D'], 'text': ['188 triệu phrăng', '187 triệu phrăng', '185 triệu phrăng', '184 triệu phrăng']}",D